cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'neovim/neovim'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'elixir'
brew 'git'
brew 'git-flow-avh'
brew 'go'
brew 'heroku'
brew 'neovim/neovim/neovim'
brew 'node'
brew 'npm'
brew 'nvm'
brew 'pandoc'
brew 'python'
brew 'python3'
brew 'pyenv'
brew 'reattach-to-user-namespace'
brew 'ruby'
brew 'siege'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'zsh'

cask 'amethyst'
cask 'bartender'
cask 'dropbox'
cask 'firefoxdeveloperedition'
cask 'google-chrome'
cask 'iterm2'
cask 'monodraw'
cask 'poedit'
cask 'reactotron'
cask 'selfcontrol'
cask 'slack'
cask 'spotify'
cask 'virtualbox'
cask 'android-studio'

# TODO: missing
# hex friend
# macvim
# self control
