cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/cask'

brew 'dnsmasq'
brew 'elixir'
# brew 'elm'
brew 'fd'
brew 'git'
brew 'git-flow-avh'
# brew 'go'
# brew 'heroku'
brew 'node'
brew 'nim'
brew 'npm'
brew 'nvm'
brew 'neovim'
brew 'pandoc'
brew 'python'
brew 'python3'
brew 'pipenv'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'reattach-to-user-namespace'
brew 'ruby'
brew 'siege'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'watchman'
brew 'wget'
brew 'yarn'

cask 'bartender'
cask 'dropbox'
cask 'firefoxdeveloperedition'
cask 'google-chrome'
cask 'iterm2'
cask 'macvim'
cask 'monodraw'
cask 'paw'
cask 'poedit'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'ngrok'

# TODO: missing
# hex friend
