cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'neovim/neovim'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'elixir'
brew 'git'
brew 'git-flow-avh'
brew 'go'
brew 'neovim/neovim/neovim'
brew 'python'
brew 'python3'
brew 'the_silver_searcher'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'node'
brew 'npm'
brew 'nvm'
brew 'siege'
brew 'tree'
brew 'zsh'

cask 'amethyst'
cask 'bartender'
cask 'dropbox'
cask 'docker-toolbox'
cask 'firefoxdeveloperedition'
cask 'google-chrome'
cask 'iterm2'
cask 'macvim' # this breaks
cask 'seil'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'virtualbox'
